# Generated by Django 5.0.4 on 2024-04-24 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('type_structure', models.CharField(choices=[('factory', 'Завод'), ('retail', 'Розничная сеть'), ('individual_entrepreneur', 'Индивидуальный предприниматель')], max_length=50, verbose_name='структура')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='задолженность')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='электронная почта')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('house_number', models.CharField(max_length=100, verbose_name='номер дома')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='продукты')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery_chains.grocerychain', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'торговое звено',
                'verbose_name_plural': 'торговые звенья',
            },
        ),
    ]
