# Generated by Django 5.0.4 on 2024-04-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_chains', '0002_alter_grocerychain_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerychain',
            name='products',
        ),
    ]
